# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: notset

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
rest_command: !include rest_commands.yaml
python_script:
