# services.yaml
double_click:
  name: Double click ZHA
  description: Detect double click ZHA event in software.
  fields:
    entity_id:
      description: The entity ID of the timer used to track clicks.
      example: timer.single_click_helper
