# services.yaml
double_click:
  name: Double click ZHA
  description: Detect double click ZHA event in software.
  fields:
    entity_id:
      description: The entity ID of the text helper used to track clicks.
      example: input_text.double_click_helper
    single_click_id:
      description: The entity ID for the timer used to trigger a single click.
      example: timer.single_click_helper
